### PR TITLE
Fix issue#482 plagiarism_turnitin_config

### PR DESCRIPTION
**Pull request by TomoTsuyuki**
Fix the issue #482

### CODE REVIEW

**Comment by TomoTsuyuki** [comment]
This needs to be deployed with https://github.com/turnitin/moodle-plagiarism_turnitin/pull/585 to fix all of issues for #482

**Comment by dwinn** [comment]
Hi @TomoTsuyuki ,

Thank you for your contribution.

I am a little concerned that this does not check for existing values in the database before changing the index. See how #585 does so. Maybe that needs to be in the code here to prevent issues if there is a null value for that field.

**Comment by TomoTsuyuki** [comment]
Hi @dwinn ,

Thanks for checking my PR.
I updated the code to check the field before changing index as #585 .

**Comment by dwinn** [comment]
Hi @TomoTsuyuki,

Thank you for the quick update, was just about to make the change myself as we're keen to get this out in our next release but then I saw you updated. We are in the final stages of preparing a release with some other community pull requests, currently aiming for early next week.

**Review by dwinn — APPROVED** [review]

**Comment by TomoTsuyuki** [comment]
Hi @dwinn 

Thank for merging.
Hope the update will save many people :)

**Pull request merged**
