### PR TITLE
Do not use settings form for Moodle 4.3 bulk completion as well

### LINKED ISSUE #685: 4.3 exception
https://moodledev.io/docs/4.3/devupdate#append-a-suffix-to-the-completion-rules

Site level activity completion defaults page errors out as a result of this

### PR DESCRIPTION
**Pull request by opitz**
This will fix #685.

### CODE REVIEW

**Review by RayCoSector — APPROVED** [review]
We added this change to plagiarism_turnitin-2024020501 code and it correctly allows the Default activity completion option within Site Admin / Courses / Default activity completion to be used without it throwing a Turnitin error

**Comment by jack-tii** [comment]
Hi @opitz thanks for your contribution, and good catch! Could you rebase this against develop so that we can get it merged?

**Comment by aspark21** [comment]
rebased on develop @jack-tii

**Comment by aspark21** [comment]
ah, target branch for merge. I think as a maintainer you should be able to change that from master to develop but otherwise I'll chase @opitz tomorrow

**Comment by jack-tii** [comment]
Thanks @aspark21, I did mean the target branch for merge, was not aware I could change that

**Review by jack-tii — APPROVED** [review]
Thanks for your contribution, will merge this

**Pull request merged**
