### PR TITLE
Fix: Use proper Modal Dialogue for eula modal

### PR DESCRIPTION
**Pull request by ixiongtii**

### CODE REVIEW

**Review by kkouchtii — APPROVED** [review]
wow, you are good, Javascript + PHP

**Comment by andrii-ilin** [comment]
@ixiongtii I think we need to add a `build` folder to `gitignore` file, builds should not be a part of the repo...

**Comment by ixiongtii** [comment]
> @ixiongtii I think we need to add a `build` folder to `gitignore` file, builds should not be a part of the repo...

Ok, I've added `amd/build` to the gitignore. Can I get another review? @andrii-ilin

**Comment by danmarsden** [comment]
Please don't do that! Moodle plugins do include the build folder. (I know this differs from some other projects) in moodles case the built amd files should be included and removing them from git will cause all sorts of problems for end-users as they will not expect it.

**Comment by andrii-ilin** [comment]
@danmarsden unexpected :-) , thanks for letting us know, @ixiongtii sorry, my bad, I didn't expect that build folders and files should be commited

**Review by andrii-ilin — APPROVED** [review]

**Comment by danmarsden** [comment]
thanks @andrii-ilin - glad I jumped in before you merged that in - although I'm surprised to see work in this space going on while other important issues like #553 are being neglected which is needed asap so that sites using Moodle 4.3 can use Turnitin (at the moment sites that have upgraded to Moodle 4.3 cannot use Turnitin code without adding that patch manually themselves.)

**Pull request merged**
