### PR TITLE
Fix group submissions

### PR DESCRIPTION
**Pull request by micaherne**
Hi, here is a patch for https://github.com/turnitin/moodle-plagiarism_turnitin/issues/288

All it does is:

1. Only saves a different submitter from the author when the submission is probably being edited by a tutor, rather than submitted by a student.
2. Looks up the user who made the latest group submission explicitly in get_links(), rather than inferring it from the group membership.

I've tested it pretty thoroughly and as far as I can see it's sound, but it would be good if someone could confirm that there are no scenarios where the queries on L705 and L811 could return a different record.

There's one outstanding edge case that it doesn't cover, which is where someone has the 'mod/assign:editothersubmission' capability on an assignment in Moodle, but Turnitin thinks they're a student. I think this scenario is probably technically possible, but I can't see why anyone would set their permissions up this way. In any case I don't think there's enough information being passed into the event handler to deal with this.

Hope it's useful.

### CODE REVIEW

**Comment by dwinn** [comment]
Hi @micaherne,

Thank you for the contribution. I have tested your branch and it looks good. It fixes the issue you reported. I agree the edge case you mention would be difficult to fix, I think we will leave that for now and look into it later if need be rather than hold this back until we can find a way to do that.

One thing though. Your pull request is to master branch but our release process requires new code to be merged into develop first. Would you be able to make a new pull request to develop?

Thanks.

**Comment by micaherne** [comment]
Hi @dwinn, thanks for reviewing the patch. I've redone it based on the develop branche, so hopefully that'll work. Cheers, Michael.

**Comment by dwinn** [comment]
Hi @micaherne,

Thanks. We'll get this out in the upcoming release. We can't give a date as we don't want to rush the testing but we aim to release around the middle of January.

**Comment by micaherne** [comment]
Thanks @dwinn. Are you planning to do anything in upgrade.php to fix the broken data?

**Comment by dwinn** [comment]
Hi @micaherne,

We will need to do some investigation work to see whether that is possible before we can do that and ensure it can't alter data that shouldn't be altered. For now the fix will go out without this.

**Comment by micaherne** [comment]
Thanks @dwinn, that's good to know.

**Pull request merged**
